# daima/arch/arm/Makefile
CROSS_COMPILE ?= arm-linux-gnueabihf-
DAIMA_CFLAGS := -I$(DAIMA_DIR) -I$(DAIMA_DIR)/include -I$(DAIMA_DIR)/init \
    -I$(DAIMA_DIR)/kernel -I$(DAIMA_DIR)/kernel/time \
    -I$(DAIMA_DIR)/ipc -I$(DAIMA_DIR)/lib -I$(DAIMA_DIR)/net -I$(DAIMA_DIR)/fs
