# scripts/Makefile.build
# 处理单个目录的 obj-y

include $(TOPDIR)/scripts/Kbuild.include

src := $(obj)
kbuild-dir := $(if $(filter /%,$(src)),$(src),$(srctree)/$(src))

include $(kbuild-dir)/Makefile

__obj-y := $(obj-y)

# 递归进入子目录
__subdir-y := $(patsubst %/,%,$(filter %/, $(obj-y)))
obj-y := $(filter-out %/, $(obj-y))
subdir-obj-y :=

# 编译当前目录的 .c → .o
targets := $(obj-y)
obj-y := $(addprefix $(obj)/, $(obj-y))

quiet_cmd_cc_o_c = CC      $@
      cmd_cc_o_c = $(CC) $(DAIMA_CFLAGS) -c -o $@ $<

.PHONY: __build subdirs $(patsubst %, _subdir_%, $(__subdir-y))
ifeq ($(KBUILD_DOC_ONLY),1)
__build: subdirs
	@:
else
__build: $(obj-y) subdirs
	@:
endif

$(obj)/%.o: $(src)/%.c
	$(call cmd,cc_o_c)

subdirs: $(patsubst %, _subdir_%, $(__subdir-y))
_subdir_%:
	$(Q)$(MAKE) $(build)=$(obj)/$*
